### ISSUE TITLE
Request to install perf on ACAD1

### ISSUE THREAD

**Issue by muslih14** [ACAD-UofA/Bioinformatics-Wiki#16]
Linux perf command, also called perf_events. perf is powerful: it can instrument CPU performance counters, tracepoints, kprobes, and uprobes (dynamic tracing). It is capable of lightweight profiling. 

This command will be perfect for my benchmarking project, allowing me to profile time used as well as cpu, I/O and memory usage in one go plus perform stats on the usage numbers too.

I've tried but have been unable to install it myself.

**Comment by grahamgower** [comment]
I don't think this is the tool you want. Perf is included with the linux kernel for system level instrumentation. In order to get the most out of it you'll probably want to take an OS course first.

In terms of actually getting it installed and running it though, this will depend on having a more recent linux kernel installed on the server(s). The ACAD servers are running linux kernel version 2.6.32-something.el6, a kernel distributed by RedHat. This predates the earliest linux kernel with perf_events support (2.6.36). Maybe RedHat backported this framework into their heavily patched server kernels, I don't know. In any event, you would need to ask ITS about getting this installed.

Simply running a program using `/usr/bin/time` is sufficient to give you the cpu and memory usage of the program. Note that you will need to run it as `/usr/bin/time`, because the bash shell (the default) has a shell builtin with the name `time` that is far less informative. E.g.
```
$ /usr/bin/time sleep 5       
0.00user 0.00system 0:05.00elapsed 0%CPU (0avgtext+0avgdata 6608maxresident)k
0inputs+0outputs (0major+83minor)pagefaults 0swaps
```
Above, I have timed the `sleep 5` command. From the output, you can see that there was very little cpu usage. This is not surprising, because the `sleep 5` command just does nothing for 5 seconds. The peak memory usage was 6608 kb. You can look up details about the other fields in the manual page: [time(1)](http://man7.org/linux/man-pages/man1/time.1.html). It can even give you I/O stats!
