### ISSUE TITLE
Permissions on data backup directory

### ISSUE THREAD

**Issue by laam21** [ACAD-UofA/Bioinformatics-Wiki#5]
Hi,
The  permissions on the following directory do not allow me to update/ read/add/modify some directories in the Metagenomic backup. 
Is it possible to change ownership to user a1654837?
Thanks,
LA

**Comment by grahamgower** [comment]
Which directory was that?  @yassineS has the ability to change permissions.

**Comment by laam21** [comment]
Sorry, I forgot to include the path. The directory is:
/data/acad/Luis_DC_backup/METAGENOMICS_Backup/

but might as well ask to change the whole backup: /data/acad/Luis_DC_backup

Thanks guys!

**Comment by yassineS** [comment]
Done, I gave you ownership of the folder.


Best,
Yassine

On 6 Jul 2017 at 2:18 pm, laam21 <notifications@github.com> wrote:


Sorry, I forgot to include the path. The directory is:
/data/acad/Luis_DC_backup/METAGENOMICS_Backup/

but might as well ask to change the whole backup: /data/acad/Luis_DC_backup

Thanks guys!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ACAD-UofA/Bioinformatics-Wiki/issues/5#issuecomment-313294092>,
or mute the thread

**Comment by laam21** [comment]
Thanks!
